/* SHADOWREACH · Forge UX V271
   Bounded, background-safe visual loot authority inside Forge.
   Keeps V270 layout/hammer design, caps visual backlog and preserves kept results when the app is backgrounded.
   No economy/progression/save changes. No overlay, no MutationObserver, no hot-loader.
*/
(function(){
'use strict';
if(window.__srForgeUXV271)return;window.__srForgeUXV271=true;
if(typeof S==='undefined'||!S.forge||typeof forgeSummon!=='function')return;

var reduced=false;try{reduced=!!matchMedia('(prefers-reduced-motion: reduce)').matches;}catch(_){}
var nativeForgeSummon=forgeSummon;
var nativeFilter=(typeof showForgeFilterPicker==='function')?showForgeFilterPicker:null;
var nativeAutoAct=(typeof ACT!=='undefined'&&ACT&&typeof ACT.autoForge==='function')?ACT.autoForge:null;
var BATCHES=[1,3,5,10],MAX_VISIBLE=5,KEEP_LIMIT=30,MAX_TRANSIENT=4,MAX_PENDING=12;
var STACK_START_X=34,STACK_STEP_X=24,STACK_START_Y=4,STACK_STEP_Y=1;
var kept=[],pendingResults=[],suspendedKept=[],activeTransients=[],timers=new Set();
var rootNode=null,stackNode=null,transientNode=null,overflowNode=null,toolNode=null,watchTimer=0,impactTimer=0;
var RARITY_C={COMMUN:'#9aa7bb',PEU_COMMUN:'#48c77a',RARE:'#4aa3ff',EPIQUE:'#b15cf6',MYTHIQUE:'#ff7a45',ARTEFACT:'#43c98b',LEGENDAIRE:'#f1c75b',INFERNAL:'#e5484d',IMMORTEL:'#d96cff',DIVIN:'#f7b52e'};
var SLOT_IMG={weapon:'art/icons/arme.png',arme:'art/icons/arme.png',helmet:'art/icons/casque.png',casque:'art/icons/casque.png',armor:'art/icons/armure.png',armure:'art/icons/armure.png',gloves:'art/icons/gants.png',gants:'art/icons/gants.png',boots:'art/icons/bottes.png',bottes:'art/icons/bottes.png',necklace:'art/icons/accessoire.png',collier:'art/icons/accessoire.png',ring:'art/icons/accessoire.png',anneau:'art/icons/accessoire.png',belt:'art/icons/accessoire.png',ceinture:'art/icons/accessoire.png',accessory:'art/icons/accessoire.png',accessoire:'art/icons/accessoire.png'};
var SLOT_LABEL={weapon:'Arme',arme:'Arme',helmet:'Casque',casque:'Casque',armor:'Armure',armure:'Armure',gloves:'Gants',gants:'Gants',boots:'Bottes',bottes:'Bottes',necklace:'Collier',collier:'Collier',ring:'Anneau',anneau:'Anneau',belt:'Ceinture',ceinture:'Ceinture',accessory:'Accessoire',accessoire:'Accessoire'};

function batch(){var n=Math.floor(Number(S.forge.autoBatch)||1);return BATCHES.indexOf(n)>=0?n:1;}
function persistBatch(n){n=Math.floor(Number(n)||1);if(BATCHES.indexOf(n)<0)n=1;S.forge.autoBatch=n;try{if(typeof saveNow==='function')saveNow();}catch(_){}try{if(typeof scheduleRender==='function')scheduleRender();}catch(_){} }
function norm(v){return String(v==null?'':v).trim().toUpperCase().replace(/[ÉÈÊË]/g,'E').replace(/[ÀÂÄ]/g,'A').replace(/[ÙÛÜ]/g,'U').replace(/[ÎÏ]/g,'I').replace(/[ÔÖ]/g,'O').replace(/[^A-Z_]/g,'_');}
function col(v){var k=norm(v);if(k==='PEU__COMMUN')k='PEU_COMMUN';return RARITY_C[k]||'#8fa3bf';}
function img(slot){return SLOT_IMG[String(slot||'').toLowerCase()]||'art/icons/accessoire.png';}
function label(slot){return SLOT_LABEL[String(slot||'').toLowerCase()]||'Équipement';}
function fmt2(v){var n=Number(v||0);if(!isFinite(n))return String(v||'');if(Math.abs(n)>=1000000)return(n/1000000).toFixed(n>=10000000?0:1)+'M';if(Math.abs(n)>=1000)return(n/1000).toFixed(n>=10000?0:1)+'K';return Math.round(n).toLocaleString('fr-FR');}
function reserve(){return document.querySelector('#homeForge .srForgeLootReserve266');}
function later(fn,ms){var id=setTimeout(function(){timers.delete(id);fn();},ms);timers.add(id);return id;}
function clearTimers(){timers.forEach(function(id){clearTimeout(id);});timers.clear();if(impactTimer){clearTimeout(impactTimer);impactTimer=0;}}

function buildRoot(){
  if(rootNode)return rootNode;
  rootNode=document.createElement('div');rootNode.id='srForgeLoot271';rootNode.className='srForgeLootZone271';rootNode.setAttribute('aria-live','polite');
  rootNode.innerHTML='<div class="srForgeStack271"></div><div class="srForgeTransient271"></div><div class="srForgeTool271" aria-hidden="true"><div class="srForgeGlow271"></div><div class="srForgeHammer271"><i class="head"></i><i class="handle"></i></div><div class="srForgeAnvil271"><i></i></div><div class="srForgeSpark271 s1"></div><div class="srForgeSpark271 s2"></div><div class="srForgeSpark271 s3"></div><div class="srForgeSpark271 s4"></div><div class="srForgeSpark271 s5"></div></div><div class="srForgeOverflow271" hidden></div>';
  stackNode=rootNode.querySelector('.srForgeStack271');transientNode=rootNode.querySelector('.srForgeTransient271');overflowNode=rootNode.querySelector('.srForgeOverflow271');toolNode=rootNode.querySelector('.srForgeTool271');syncTool();return rootNode;
}
function mountRoot(){var h=reserve();if(!h)return null;var root=buildRoot();if(root.parentNode!==h)h.replaceChildren(root);syncTool();return root;}
function syncTool(){if(toolNode)toolNode.classList.toggle('auto',!!S.forge.autoForge&&!reduced);}
function impactBatch(count){if(!mountRoot()||!toolNode||reduced)return;toolNode.classList.remove('impact','burst');void toolNode.offsetWidth;if(Number(count||0)>=5)toolNode.classList.add('burst');toolNode.classList.add('impact');if(impactTimer)clearTimeout(impactTimer);impactTimer=setTimeout(function(){impactTimer=0;if(toolNode){toolNode.classList.remove('impact','burst');syncTool();}},390);}
function layoutStack(newNode){if(!stackNode)return;var total=kept.length,start=Math.max(0,total-MAX_VISIBLE),hidden=start;kept.forEach(function(entry,i){var show=i>=start;entry.node.hidden=!show;if(!show)return;var vi=i-start;entry.node.style.left=(STACK_START_X+vi*STACK_STEP_X)+'px';entry.node.style.top=(STACK_START_Y+vi*STACK_STEP_Y)+'px';entry.node.style.zIndex=String(vi+1);});if(overflowNode){overflowNode.hidden=hidden<=0;overflowNode.textContent=hidden>0?'+'+hidden:'';}if(newNode&&!reduced){newNode.classList.remove('join');void newNode.offsetWidth;newNode.classList.add('join');later(function(){if(newNode)newNode.classList.remove('join');},220);}}
function stackCard(r){var d=document.createElement('div');d.className='srForgeStackCard271';d.style.setProperty('--r',col(r.rarity));d.title=label(r.slot)+' · '+String(r.rarity||'').replace(/_/g,' ');d.innerHTML='<img src="'+img(r.slot)+'" alt=""><span>'+String(r.rarity||'').replace(/_/g,' ').slice(0,3)+'</span>';return d;}
function addKept(r,animate){if(!r||r.recycled||!mountRoot())return false;var node=stackCard(r);stackNode.appendChild(node);kept.push({data:r,node:node});if(kept.length>KEEP_LIMIT){var old=kept.shift();if(old&&old.node&&old.node.parentNode)old.node.remove();}layoutStack(animate===false?null:node);startWatch();return true;}
function stashKept(r){if(!r||r.recycled)return;suspendedKept.push(r);if(suspendedKept.length>KEEP_LIMIT)suspendedKept.shift();}
function restoreSuspended(){if(document.hidden||!reserve()||!suspendedKept.length)return;var arr=suspendedKept.splice(0);arr.forEach(function(r){addKept(r,false);});}
function compactPending(){while(pendingResults.length>MAX_PENDING){var r=pendingResults.shift();if(r&&!r.recycled)addKept(r,false);}}
function transientCard(r){var rec=!!r.recycled,d=document.createElement('div');d.className='srForgeTransientCard271 '+(rec?'recycled':'kept');d.style.setProperty('--r',col(r.rarity));d.innerHTML='<div class="srForgeTransientIcon271"><img src="'+img(r.slot)+'" alt=""></div><div class="srForgeTransientText271"><b>'+label(r.slot)+'</b><small>'+String(r.rarity||'').replace(/_/g,' ')+(r.power!=null?' · '+fmt2(r.power):'')+'</small>'+(rec&&r.dust!=null?'<em>+'+fmt2(r.dust)+' poussière</em>':'')+'</div>';return d;}
function layoutTransients(){activeTransients.forEach(function(entry,i){entry.node.style.setProperty('--tx',(i*13)+'px');entry.node.style.setProperty('--ty',(i*1.5)+'px');entry.node.style.zIndex=String(20+i);});}
function removeTransient(entry){var i=activeTransients.indexOf(entry);if(i>=0)activeTransients.splice(i,1);if(entry&&entry.node&&entry.node.parentNode)entry.node.remove();layoutTransients();pumpQueue();}
function startResult(r){if(document.hidden||!mountRoot())return false;var d=transientCard(r),entry={data:r,node:d};activeTransients.push(entry);transientNode.appendChild(d);layoutTransients();requestAnimationFrame(function(){requestAnimationFrame(function(){if(d.isConnected)d.classList.add('enter');});});if(r.recycled){later(function(){if(d.isConnected)d.classList.add('recycleOut');later(function(){removeTransient(entry);},reduced?110:400);},reduced?150:500);}else{later(function(){if(d.isConnected)d.classList.add('merge');later(function(){removeTransient(entry);addKept(r,true);},reduced?90:200);},reduced?160:520);}return true;}
function pumpQueue(){if(document.hidden||!reserve())return;compactPending();while(activeTransients.length<MAX_TRANSIENT&&pendingResults.length){var r=pendingResults.shift();if(!startResult(r))break;}}
function enqueue(res){if(!Array.isArray(res)||!res.length)return;var batchResults=res.slice(0,20);if(document.hidden){batchResults.forEach(stashKept);return;}if(!reserve())return;Array.prototype.push.apply(pendingResults,batchResults);compactPending();impactBatch(batchResults.length);pumpQueue();startWatch();}
function suspendVisuals(){pendingResults.forEach(stashKept);activeTransients.forEach(function(e){stashKept(e&&e.data);});clearTimers();pendingResults.length=0;activeTransients.forEach(function(e){if(e.node&&e.node.parentNode)e.node.remove();});activeTransients.length=0;if(toolNode)toolNode.classList.remove('impact','burst');syncTool();}
function clearTransientOnly(){clearTimers();pendingResults.length=0;suspendedKept.length=0;activeTransients.forEach(function(e){if(e.node&&e.node.parentNode)e.node.remove();});activeTransients.length=0;if(toolNode)toolNode.classList.remove('impact','burst');syncTool();}
function resetUI(clearKept){clearTransientOnly();if(clearKept){kept.forEach(function(e){if(e.node&&e.node.parentNode)e.node.remove();});kept.length=0;}if(rootNode&&rootNode.parentNode)rootNode.remove();if(clearKept){rootNode=stackNode=transientNode=overflowNode=toolNode=null;}}
function startWatch(){if(watchTimer)return;watchTimer=setInterval(function(){var h=reserve();if(!h){resetUI(true);clearInterval(watchTimer);watchTimer=0;return;}if(rootNode&&rootNode.parentNode!==h)mountRoot();syncTool();if(!document.hidden){restoreSuspended();pumpQueue();}if(!kept.length&&!pendingResults.length&&!suspendedKept.length&&!activeTransients.length&&!timers.size&&!S.forge.autoForge){clearInterval(watchTimer);watchTimer=0;}},140);}

forgeSummon=function(){var args=Array.prototype.slice.call(arguments),requested=Math.floor(Number(args[0])||1);if(S.forge.autoForge&&requested===1&&batch()>1){try{var cost=forgeCost(S.forge.level),aff=Math.max(1,Math.floor(Number(S.minerai||0)/Math.max(1,cost)));args[0]=Math.max(1,Math.min(batch(),aff));}catch(_){args[0]=batch();}}var out=nativeForgeSummon.apply(this,args);try{enqueue(out);}catch(e){console.warn('forge queue V271 skipped',e);}return out;};
try{window.forgeSummon=forgeSummon;}catch(_){}
if(typeof ACT!=='undefined'&&ACT){if(nativeAutoAct){ACT.autoForge=function(){var out=nativeAutoAct.apply(this,arguments);later(function(){if(reserve()){mountRoot();restoreSuspended();syncTool();if(S.forge.autoForge)startWatch();}},0);return out;};}ACT.autoForgeBatch266=function(a){persistBatch(a);try{if(typeof autoForgeTimer!=='undefined'&&autoForgeTimer!==null){clearTimeout(autoForgeTimer);autoForgeTimer=null;}if(S.forge.autoForge&&typeof scheduleAutoForge==='function'&&!(window.__srAutoForgePausedForCompareV199&&window.__srAutoForgePausedForCompareV199()))scheduleAutoForge(180);}catch(_){}if(nativeFilter)showForgeFilterPicker();};}
function injectBatch(){var toggle=document.querySelector('[data-act="forgeFilterToggle"]');if(!toggle)return;var row=toggle.parentElement;if(!row||document.getElementById('srAutoBatch266'))return;var box=document.createElement('div');box.id='srAutoBatch266';box.innerHTML='<div class="b small">Auto-Forge simultanée</div><div class="mute tiny mt2">Nombre de pièces forgées à chaque cycle AUTO.</div><div class="srBatchBtns266">'+BATCHES.map(function(n){return '<button type="button" class="srBatch266 '+(batch()===n?'on':'')+'" data-act="autoForgeBatch266" data-arg="'+n+'">×'+n+'</button>';}).join('')+'</div><div class="mute tiny mt3">Le coût reste normal par pièce. Les valeurs non débloquées sont verrouillées par ta progression.</div>';row.insertAdjacentElement('afterend',box);}
if(nativeFilter){showForgeFilterPicker=function(){var r=nativeFilter.apply(this,arguments);requestAnimationFrame(injectBatch);return r;};try{window.showForgeFilterPicker=showForgeFilterPicker;}catch(_){} }

document.addEventListener('click',function(e){var go=e.target&&e.target.closest?e.target.closest('[data-act="go"],[data-act="nav"]'):null;if(go)later(function(){if(!reserve())resetUI(true);},0);},true);
document.addEventListener('visibilitychange',function(){if(document.hidden){suspendVisuals();return;}if(reserve()&&(kept.length||suspendedKept.length||S.forge.autoForge)){mountRoot();restoreSuspended();syncTool();startWatch();}});
window.addEventListener('pagehide',function(){resetUI(true);});
['srForgeUX261Style','srForgeUX266Style','srForgeUX267Style','srForgeUX268Style','srForgeUX269Style','srForgeUX270Style','srForgeEntryAnimationV263Style','srForgeEntryAnimationV264Style'].forEach(function(id){var x=document.getElementById(id);if(x)x.remove();});

var st=document.createElement('style');st.id='srForgeUX271Style';st.textContent='\
#srForgeLoot271{position:relative;width:100%;height:62px;max-height:62px;box-sizing:border-box;pointer-events:none;overflow:hidden}\
#srForgeLoot271 .srForgeStack271,#srForgeLoot271 .srForgeTransient271{position:absolute;left:0;top:0;bottom:0;right:108px}\
#srForgeLoot271 .srForgeStack271{z-index:1}#srForgeLoot271 .srForgeTransient271{z-index:8}\
#srForgeLoot271 .srForgeStackCard271{--r:#8fa3bf;position:absolute;width:46px;height:51px;border:1.5px solid var(--r);border-radius:9px;background:linear-gradient(180deg,#18263cf7,#09111ff7);box-shadow:0 2px 6px #0008,0 0 6px color-mix(in srgb,var(--r) 20%,transparent);display:grid;place-items:center;overflow:hidden;transform-origin:50% 80%}\
#srForgeLoot271 .srForgeStackCard271.join{animation:srStackJoin271 .20s cubic-bezier(.2,.8,.3,1.08) both}\
#srForgeLoot271 .srForgeStackCard271 img{width:30px;height:30px;object-fit:contain;filter:drop-shadow(0 2px 2px #0008)}#srForgeLoot271 .srForgeStackCard271 span{position:absolute;bottom:2px;left:3px;right:3px;text-align:center;font:900 5.5px/1 system-ui;color:var(--r);text-transform:uppercase;white-space:nowrap;overflow:hidden}\
#srForgeLoot271 .srForgeOverflow271{position:absolute;z-index:10;right:105px;top:19px;min-width:27px;height:24px;padding:0 5px;border:1px solid #5b7190;border-radius:999px;background:#101a2bed;color:#e6eef9;display:grid;place-items:center;font:900 8px system-ui;box-sizing:border-box}\
#srForgeLoot271 .srForgeTransientCard271{--r:#8fa3bf;--tx:0px;--ty:0px;position:absolute;left:30px;top:4px;height:52px;width:118px;border:1.5px solid var(--r);border-radius:10px;background:linear-gradient(180deg,#182840fa,#091321fa);box-shadow:0 3px 9px #000a,0 0 8px color-mix(in srgb,var(--r) 24%,transparent);display:flex;align-items:center;gap:6px;padding:5px 7px;box-sizing:border-box;opacity:0;transform:translate(var(--tx),calc(var(--ty) + 5px)) scale(.98);filter:brightness(.92);overflow:hidden}\
#srForgeLoot271 .srForgeTransientCard271.enter{animation:srForgeEnter271 .21s cubic-bezier(.2,.82,.3,1.08) both}\
#srForgeLoot271 .srForgeTransientIcon271{width:34px;height:34px;flex:0 0 34px;border-radius:8px;background:radial-gradient(circle,color-mix(in srgb,var(--r) 15%,transparent),transparent 72%);display:grid;place-items:center}#srForgeLoot271 .srForgeTransientIcon271 img{width:31px;height:31px;object-fit:contain;filter:drop-shadow(0 2px 2px #0008)}\
#srForgeLoot271 .srForgeTransientText271{min-width:0;display:flex;flex-direction:column;gap:2px}.srForgeTransientText271 b{font:900 8px/1 Georgia,serif;color:#f4df9d;white-space:nowrap}.srForgeTransientText271 small{font:800 6px/1 system-ui;color:var(--r);white-space:nowrap}.srForgeTransientText271 em{font:900 6px/1 system-ui;color:#a8e8ff;font-style:normal;white-space:nowrap}\
#srForgeLoot271 .srForgeTransientCard271.merge{animation:none;opacity:0;transform:translate(calc(var(--tx) + 34px),var(--ty)) scale(.86);filter:brightness(1.08);transition:opacity .17s ease,transform .20s cubic-bezier(.3,.7,.4,1),filter .17s}\
#srForgeLoot271 .srForgeTransientCard271.recycleOut{animation:none;opacity:0;transform:translate(var(--tx),calc(var(--ty) - 3px)) scale(.72) rotate(-3deg);filter:grayscale(.65) blur(.7px);transition:opacity .28s ease,transform .38s ease,filter .34s ease}\
#srForgeLoot271 .srForgeTool271{position:absolute;z-index:12;right:6px;top:2px;width:94px;height:58px;border:1px solid #4b6077;border-radius:13px;background:linear-gradient(180deg,#12253aee,#081421f2);box-shadow:inset 0 0 0 1px #ffffff0b,0 4px 10px #0008,0 0 14px #ffad3b12;overflow:hidden}\
#srForgeLoot271 .srForgeGlow271{position:absolute;left:25px;bottom:-14px;width:48px;height:34px;border-radius:50%;background:radial-gradient(circle,#ffbd5555 0%,#e06e1b20 48%,transparent 72%);filter:blur(1px)}\
#srForgeLoot271 .srForgeHammer271{position:absolute;left:37px;top:5px;width:34px;height:39px;transform-origin:13px 34px;transform:rotate(-13deg);filter:drop-shadow(0 2px 2px #0009)}#srForgeLoot271 .srForgeHammer271 .head{position:absolute;left:0;top:0;width:27px;height:11px;border-radius:4px;background:linear-gradient(180deg,#eef6ff,#8fa4b9 55%,#5e7185);box-shadow:inset 0 1px 0 #fff8,0 1px 2px #000a}#srForgeLoot271 .srForgeHammer271 .handle{position:absolute;left:12px;top:9px;width:6px;height:31px;border-radius:4px;background:linear-gradient(90deg,#683919,#c47b39 45%,#e0a05b 57%,#6e3c1d)}\
#srForgeLoot271 .srForgeAnvil271{position:absolute;left:20px;bottom:6px;width:57px;height:15px;background:linear-gradient(180deg,#c0d0dd,#6f8499 48%,#405367);clip-path:polygon(0 0,72% 0,81% 20%,100% 20%,100% 48%,71% 48%,64% 100%,24% 100%,18% 57%,0 57%);filter:drop-shadow(0 2px 2px #0009)}#srForgeLoot271 .srForgeAnvil271 i{position:absolute;left:21px;top:10px;width:15px;height:7px;background:#3f5367}\
#srForgeLoot271 .srForgeSpark271{position:absolute;width:4px;height:4px;border-radius:50%;background:#ffe08a;box-shadow:0 0 8px #ff9f36;opacity:0;left:47px;top:35px}.srForgeSpark271.s2{left:54px;top:32px}.srForgeSpark271.s3{left:42px;top:31px}.srForgeSpark271.s4{left:58px;top:36px}.srForgeSpark271.s5{left:38px;top:36px}\
#srForgeLoot271 .srForgeTool271.auto:not(.impact) .srForgeHammer271{animation:srForgeHammerIdle271 1.18s ease-in-out infinite}\
#srForgeLoot271 .srForgeTool271.auto:not(.impact)::after{content:"AUTO FORGE";position:absolute;right:7px;top:5px;font:900 5.5px/1 system-ui;color:#78ed9c;letter-spacing:.5px;opacity:.9}\
#srForgeLoot271 .srForgeTool271.impact .srForgeHammer271{animation:srForgeHammerImpact271 .36s cubic-bezier(.2,.75,.3,1) both}\
#srForgeLoot271 .srForgeTool271.impact{animation:srForgeToolPulse271 .30s ease-out both}#srForgeLoot271 .srForgeTool271.impact .srForgeGlow271{animation:srForgeGlow271 .34s ease-out both}\
#srForgeLoot271 .srForgeTool271.impact .srForgeSpark271.s1{animation:srSpark1271 .30s ease-out both}#srForgeLoot271 .srForgeTool271.impact .srForgeSpark271.s2{animation:srSpark2271 .30s ease-out both}#srForgeLoot271 .srForgeTool271.impact .srForgeSpark271.s3{animation:srSpark3271 .30s ease-out both}#srForgeLoot271 .srForgeTool271.impact .srForgeSpark271.s4{animation:srSpark4271 .30s ease-out both}#srForgeLoot271 .srForgeTool271.impact .srForgeSpark271.s5{animation:srSpark5271 .30s ease-out both}\
#srForgeLoot271 .srForgeTool271.burst.impact{box-shadow:inset 0 0 0 1px #ffd66c55,0 4px 10px #0008,0 0 18px #ff9f3655}\
@keyframes srForgeEnter271{0%{opacity:0;transform:translate(var(--tx),calc(var(--ty) + 5px)) scale(.98);filter:brightness(.92)}72%{opacity:1;transform:translate(var(--tx),calc(var(--ty) - 1px)) scale(1.008);filter:brightness(1.06)}100%{opacity:1;transform:translate(var(--tx),var(--ty));filter:none}}@keyframes srStackJoin271{0%{opacity:.28;transform:translateX(-3px) scale(.97)}100%{opacity:1;transform:none}}\
@keyframes srForgeHammerIdle271{0%,62%,100%{transform:rotate(-13deg)}74%{transform:rotate(12deg) translateY(1px)}82%{transform:rotate(-3deg)}}@keyframes srForgeHammerImpact271{0%{transform:rotate(-23deg)}46%{transform:rotate(19deg) translateY(3px)}61%{transform:rotate(8deg) translateY(1px)}100%{transform:rotate(-13deg)}}@keyframes srForgeToolPulse271{0%,100%{box-shadow:inset 0 0 0 1px #ffffff0b,0 4px 10px #0008,0 0 14px #ffad3b12}52%{box-shadow:inset 0 0 0 1px #ffd66c66,0 4px 10px #0008,0 0 22px #ff9f3666}}@keyframes srForgeGlow271{0%{opacity:.35;transform:scale(.8)}45%{opacity:1;transform:scale(1.25)}100%{opacity:.5;transform:scale(1)}}\
@keyframes srSpark1271{0%{opacity:0;transform:translate(0,0) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(-14px,-13px) scale(.2)}}@keyframes srSpark2271{0%{opacity:0;transform:translate(0,0) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(15px,-11px) scale(.2)}}@keyframes srSpark3271{0%{opacity:0;transform:translate(0,0) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(-3px,-17px) scale(.2)}}@keyframes srSpark4271{0%{opacity:0;transform:translate(0,0) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(18px,-4px) scale(.2)}}@keyframes srSpark5271{0%{opacity:0;transform:translate(0,0) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(-18px,-5px) scale(.2)}}\
#srAutoBatch266{margin-top:8px;padding:8px;border:1px solid #314a70;border-radius:12px;background:#0d1728}.srBatchBtns266{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:6px}.srBatch266{appearance:none;border:1px solid #405a80;background:#111d31;color:#b8c6dc;border-radius:9px;padding:7px 2px;font-size:10px;font-weight:900}.srBatch266.on{border-color:#e8b44a;color:#ffe2a0;background:#2a210d;box-shadow:0 0 0 1px #e8b44a55 inset}\
@media(max-width:390px){#srForgeLoot271{height:58px;max-height:58px}#srForgeLoot271 .srForgeStack271,#srForgeLoot271 .srForgeTransient271{right:98px}#srForgeLoot271 .srForgeStackCard271{width:43px;height:48px}#srForgeLoot271 .srForgeStackCard271 img{width:28px;height:28px}#srForgeLoot271 .srForgeTransientCard271{height:49px;width:106px;left:27px}#srForgeLoot271 .srForgeTransientIcon271{width:31px;height:31px;flex-basis:31px}#srForgeLoot271 .srForgeTransientIcon271 img{width:28px;height:28px}#srForgeLoot271 .srForgeTool271{right:4px;width:86px;height:54px;top:2px}#srForgeLoot271 .srForgeHammer271{left:33px;top:5px}#srForgeLoot271 .srForgeAnvil271{left:17px;width:53px}#srForgeLoot271 .srForgeOverflow271{right:94px}}\
@media(prefers-reduced-motion:reduce){#srForgeLoot271 *{animation:none!important;transition:opacity .1s linear!important}.srForgeTransientCard271.enter{opacity:1!important;transform:none!important;filter:none!important}.srForgeTool271{opacity:.82}}';document.head.appendChild(st);

if(reserve()){mountRoot();restoreSuspended();if(S.forge.autoForge)startWatch();}
window.__srForgeUXV271={batch:batch,enqueue:enqueue,clear:function(){resetUI(true);},kept:function(){return kept.map(function(e){return e.data;});},pending:function(){return pendingResults.length;},suspended:function(){return suspendedKept.length;},impact:function(){impactBatch(1);},version:271};
})();