/* SHADOWREACH · Forge UX V267
   Compact stacked loot authority inside Forge.
   Kept items accumulate in a compact overlapping stack; recycled items animate then disappear.
   No economy/progression/save changes. No overlay, no MutationObserver, no hot-loader.
*/
(function(){
'use strict';
if(window.__srForgeUXV267)return;window.__srForgeUXV267=true;
if(typeof S==='undefined'||!S.forge||typeof forgeSummon!=='function')return;
var reduced=false;try{reduced=!!matchMedia('(prefers-reduced-motion: reduce)').matches;}catch(_){}
var nativeForgeSummon=forgeSummon;
var nativeFilter=(typeof showForgeFilterPicker==='function')?showForgeFilterPicker:null;
var BATCHES=[1,3,5,10],MAX_VISIBLE=7,KEEP_LIMIT=30,STAGGER=reduced?0:70;
var kept=[],timers=[],hostNode=null,rootNode=null,stackNode=null,transientNode=null,watchTimer=0;
var RARITY_C={COMMUN:'#9aa7bb',PEU_COMMUN:'#48c77a',RARE:'#4aa3ff',EPIQUE:'#b15cf6',MYTHIQUE:'#ff7a45',ARTEFACT:'#43c98b',LEGENDAIRE:'#f1c75b',INFERNAL:'#e5484d',IMMORTEL:'#d96cff',DIVIN:'#f7b52e'};
var SLOT_IMG={weapon:'art/icons/arme.png',arme:'art/icons/arme.png',helmet:'art/icons/casque.png',casque:'art/icons/casque.png',armor:'art/icons/armure.png',armure:'art/icons/armure.png',gloves:'art/icons/gants.png',gants:'art/icons/gants.png',boots:'art/icons/bottes.png',bottes:'art/icons/bottes.png',necklace:'art/icons/accessoire.png',collier:'art/icons/accessoire.png',ring:'art/icons/accessoire.png',anneau:'art/icons/accessoire.png',belt:'art/icons/accessoire.png',ceinture:'art/icons/accessoire.png',accessory:'art/icons/accessoire.png',accessoire:'art/icons/accessoire.png'};
var SLOT_LABEL={weapon:'Arme',arme:'Arme',helmet:'Casque',casque:'Casque',armor:'Armure',armure:'Armure',gloves:'Gants',gants:'Gants',boots:'Bottes',bottes:'Bottes',necklace:'Collier',collier:'Collier',ring:'Anneau',anneau:'Anneau',belt:'Ceinture',ceinture:'Ceinture',accessory:'Accessoire',accessoire:'Accessoire'};
function batch(){var n=Math.floor(Number(S.forge.autoBatch)||1);return BATCHES.indexOf(n)>=0?n:1;}
function persistBatch(n){n=Math.floor(Number(n)||1);if(BATCHES.indexOf(n)<0)n=1;S.forge.autoBatch=n;try{if(typeof saveNow==='function')saveNow();}catch(_){}try{if(typeof scheduleRender==='function')scheduleRender();}catch(_){} }
function norm(v){return String(v==null?'':v).trim().toUpperCase().replace(/[ÉÈÊË]/g,'E').replace(/[ÀÂÄ]/g,'A').replace(/[ÙÛÜ]/g,'U').replace(/[ÎÏ]/g,'I').replace(/[ÔÖ]/g,'O').replace(/[^A-Z_]/g,'_');}
function col(v){var k=norm(v);if(k==='PEU__COMMUN')k='PEU_COMMUN';return RARITY_C[k]||'#8fa3bf';}
function img(slot){return SLOT_IMG[String(slot||'').toLowerCase()]||'art/icons/accessoire.png';}
function label(slot){return SLOT_LABEL[String(slot||'').toLowerCase()]||'Équipement';}
function fmt2(v){var n=Number(v||0);if(!isFinite(n))return String(v||'');if(Math.abs(n)>=1000000)return(n/1000000).toFixed(n>=10000000?0:1)+'M';if(Math.abs(n)>=1000)return(n/1000).toFixed(n>=10000?0:1)+'K';return Math.round(n).toLocaleString('fr-FR');}
function reserve(){return document.querySelector('#homeForge .srForgeLootReserve266');}
function clearTimers(){timers.forEach(function(t){clearTimeout(t);});timers.length=0;}
function ensureRoot(){var h=reserve();if(!h)return null;if(hostNode!==h||!rootNode||rootNode.parentNode!==h){hostNode=h;h.replaceChildren();rootNode=document.createElement('div');rootNode.id='srForgeLoot267';rootNode.className='srForgeLootZone267';rootNode.setAttribute('aria-live','polite');rootNode.innerHTML='<div class="srForgeStack267"></div><div class="srForgeTransient267"></div><div class="srForgeOverflow267" hidden></div>';h.appendChild(rootNode);stackNode=rootNode.querySelector('.srForgeStack267');transientNode=rootNode.querySelector('.srForgeTransient267');renderStack();}return rootNode;}
function stackCard(r,i){var d=document.createElement('div');d.className='srForgeStackCard267';d.style.setProperty('--r',col(r.rarity));d.style.left=(5+i*18)+'px';d.style.zIndex=String(i+1);d.title=label(r.slot)+' · '+String(r.rarity||'').replace(/_/g,' ');d.innerHTML='<img src="'+img(r.slot)+'" alt=""><span>'+String(r.rarity||'').replace(/_/g,' ').slice(0,3)+'</span>';return d;}
function renderStack(){if(!rootNode||!stackNode)return;stackNode.replaceChildren();var visible=kept.slice(-MAX_VISIBLE),hidden=Math.max(0,kept.length-visible.length);visible.forEach(function(r,i){stackNode.appendChild(stackCard(r,i));});var badge=rootNode.querySelector('.srForgeOverflow267');if(hidden>0){badge.hidden=false;badge.textContent='+'+hidden;}else{badge.hidden=true;badge.textContent='';}}
function transientCard(r){var rec=!!r.recycled,d=document.createElement('div');d.className='srForgeTransientCard267 '+(rec?'recycled':'kept');d.style.setProperty('--r',col(r.rarity));d.innerHTML='<div class="srForgeTransientIcon267"><img src="'+img(r.slot)+'" alt=""></div><div class="srForgeTransientText267"><b>'+label(r.slot)+'</b><small>'+String(r.rarity||'').replace(/_/g,' ')+(r.power!=null?' · '+fmt2(r.power):'')+'</small>'+(rec&&r.dust!=null?'<em>+'+fmt2(r.dust)+' poussière</em>':'')+'</div>';return d;}
function addKept(r){kept.push(r);if(kept.length>KEEP_LIMIT)kept=kept.slice(-KEEP_LIMIT);if(ensureRoot())renderStack();}
function animateResult(r,delay){var t=setTimeout(function(){if(document.hidden||!ensureRoot())return;var d=transientCard(r);transientNode.appendChild(d);requestAnimationFrame(function(){requestAnimationFrame(function(){d.classList.add('enter');});});if(r.recycled){var t2=setTimeout(function(){d.classList.add('recycleOut');var t3=setTimeout(function(){if(d.parentNode)d.remove();},reduced?120:440);timers.push(t3);},reduced?180:520);timers.push(t2);}else{var t4=setTimeout(function(){d.classList.add('merge');var t5=setTimeout(function(){if(d.parentNode)d.remove();addKept(r);},reduced?100:220);timers.push(t5);},reduced?180:560);timers.push(t4);}},delay);timers.push(t);}
function enqueue(res){if(!Array.isArray(res)||!res.length||document.hidden||!reserve())return;res.slice(0,20).forEach(function(r,i){animateResult(r,i*STAGGER);});startWatch();}
function resetUI(clearKept){clearTimers();if(clearKept)kept.length=0;if(rootNode&&rootNode.parentNode)rootNode.remove();hostNode=rootNode=stackNode=transientNode=null;}
function startWatch(){if(watchTimer)return;watchTimer=setInterval(function(){if(!reserve()){resetUI(true);clearInterval(watchTimer);watchTimer=0;return;}if((kept.length||timers.length)&&(!rootNode||rootNode.parentNode!==reserve()))ensureRoot();},180);}
forgeSummon=function(){var args=Array.prototype.slice.call(arguments),requested=Math.floor(Number(args[0])||1);if(S.forge.autoForge&&requested===1&&batch()>1){try{var cost=forgeCost(S.forge.level),aff=Math.max(1,Math.floor(Number(S.minerai||0)/Math.max(1,cost)));args[0]=Math.max(1,Math.min(batch(),aff));}catch(_){args[0]=batch();}}var out=nativeForgeSummon.apply(this,args);try{enqueue(out);}catch(e){console.warn('forge stacked loot V267 skipped',e);}return out;};
try{window.forgeSummon=forgeSummon;}catch(_){}
if(typeof ACT!=='undefined'&&ACT){ACT.autoForgeBatch266=function(a){persistBatch(a);try{if(typeof autoForgeTimer!=='undefined'&&autoForgeTimer!==null){clearTimeout(autoForgeTimer);autoForgeTimer=null;}if(S.forge.autoForge&&typeof scheduleAutoForge==='function'&&!(window.__srAutoForgePausedForCompareV199&&window.__srAutoForgePausedForCompareV199()))scheduleAutoForge(180);}catch(_){}if(nativeFilter)showForgeFilterPicker();};}
function injectBatch(){var toggle=document.querySelector('[data-act="forgeFilterToggle"]');if(!toggle)return;var row=toggle.parentElement;if(!row||document.getElementById('srAutoBatch266'))return;var box=document.createElement('div');box.id='srAutoBatch266';box.innerHTML='<div class="b small">Auto-Forge simultanée</div><div class="mute tiny mt2">Nombre de pièces forgées à chaque cycle AUTO.</div><div class="srBatchBtns266">'+BATCHES.map(function(n){return '<button type="button" class="srBatch266 '+(batch()===n?'on':'')+'" data-act="autoForgeBatch266" data-arg="'+n+'">×'+n+'</button>';}).join('')+'</div><div class="mute tiny mt3">Le coût reste normal par pièce. Les valeurs non débloquées sont verrouillées par ta progression.</div>';row.insertAdjacentElement('afterend',box);}
if(nativeFilter){showForgeFilterPicker=function(){var r=nativeFilter.apply(this,arguments);requestAnimationFrame(injectBatch);return r;};try{window.showForgeFilterPicker=showForgeFilterPicker;}catch(_){} }
document.addEventListener('click',function(e){var go=e.target&&e.target.closest?e.target.closest('[data-act="go"],[data-act="nav"]'):null;if(go)setTimeout(function(){if(!reserve())resetUI(true);},0);},true);
document.addEventListener('visibilitychange',function(){if(document.hidden)resetUI(true);});window.addEventListener('pagehide',function(){resetUI(true);});
['srForgeUX261Style','srForgeUX266Style','srForgeEntryAnimationV263Style','srForgeEntryAnimationV264Style'].forEach(function(id){var x=document.getElementById(id);if(x)x.remove();});
var st=document.createElement('style');st.id='srForgeUX267Style';st.textContent='\
#srForgeLoot267{position:relative;width:100%;height:62px;max-height:62px;box-sizing:border-box;pointer-events:none;overflow:hidden}\
#srForgeLoot267 .srForgeStack267,#srForgeLoot267 .srForgeTransient267{position:absolute;inset:0}\
#srForgeLoot267 .srForgeStack267{z-index:1}#srForgeLoot267 .srForgeTransient267{z-index:8}\
#srForgeLoot267 .srForgeStackCard267{--r:#8fa3bf;position:absolute;top:5px;width:48px;height:52px;border:1.5px solid var(--r);border-radius:9px;background:linear-gradient(180deg,#18263cf7,#09111ff7);box-shadow:0 3px 8px #0009,0 0 7px color-mix(in srgb,var(--r) 24%,transparent);display:grid;place-items:center;overflow:hidden;transform-origin:50% 80%;animation:srStackJoin267 .22s cubic-bezier(.2,.85,.3,1.12) both}\
#srForgeLoot267 .srForgeStackCard267 img{width:31px;height:31px;object-fit:contain;filter:drop-shadow(0 2px 2px #0009)}#srForgeLoot267 .srForgeStackCard267 span{position:absolute;bottom:2px;left:3px;right:3px;text-align:center;font:900 5.5px/1 system-ui;color:var(--r);text-transform:uppercase;white-space:nowrap;overflow:hidden}\
#srForgeLoot267 .srForgeOverflow267{position:absolute;z-index:6;right:4px;top:19px;min-width:27px;height:24px;padding:0 5px;border:1px solid #5b7190;border-radius:999px;background:#101a2bed;color:#e6eef9;display:grid;place-items:center;font:900 8px system-ui;box-sizing:border-box}\
#srForgeLoot267 .srForgeTransientCard267{--r:#8fa3bf;position:absolute;left:5px;top:4px;height:54px;max-width:145px;min-width:118px;border:1.5px solid var(--r);border-radius:10px;background:linear-gradient(180deg,#182840fa,#091321fa);box-shadow:0 4px 11px #000b,0 0 10px color-mix(in srgb,var(--r) 28%,transparent);display:flex;align-items:center;gap:6px;padding:5px 7px;box-sizing:border-box;opacity:0;transform:translateY(7px) scale(.95);filter:brightness(.9);overflow:hidden}\
#srForgeLoot267 .srForgeTransientCard267.enter{animation:srForgeEnter267 .22s cubic-bezier(.2,.85,.3,1.12) both}\
#srForgeLoot267 .srForgeTransientIcon267{width:38px;height:38px;flex:0 0 38px;border-radius:8px;background:radial-gradient(circle,color-mix(in srgb,var(--r) 17%,transparent),transparent 72%);display:grid;place-items:center}#srForgeLoot267 .srForgeTransientIcon267 img{width:34px;height:34px;object-fit:contain;filter:drop-shadow(0 2px 2px #0009)}\
#srForgeLoot267 .srForgeTransientText267{min-width:0;display:flex;flex-direction:column;gap:2px}.srForgeTransientText267 b{font:900 8px/1 Georgia,serif;color:#f4df9d;white-space:nowrap}.srForgeTransientText267 small{font:800 6px/1 system-ui;color:var(--r);white-space:nowrap}.srForgeTransientText267 em{font:900 6px/1 system-ui;color:#a8e8ff;font-style:normal;white-space:nowrap}\
#srForgeLoot267 .srForgeTransientCard267.merge{animation:none;opacity:0;transform:translateX(22px) scale(.62);filter:brightness(1.15);transition:opacity .18s ease,transform .22s cubic-bezier(.3,.7,.4,1),filter .18s}\
#srForgeLoot267 .srForgeTransientCard267.recycleOut{animation:none;opacity:0;transform:translateY(-4px) scale(.58) rotate(-5deg);filter:grayscale(.7) blur(1px);transition:opacity .32s ease,transform .42s ease,filter .4s ease}\
@keyframes srForgeEnter267{0%{opacity:0;transform:translateY(7px) scale(.95);filter:brightness(.9)}72%{opacity:1;transform:translateY(-1px) scale(1.02);filter:brightness(1.1)}100%{opacity:1;transform:none;filter:none}}@keyframes srStackJoin267{0%{opacity:0;transform:translateX(-8px) scale(.82)}100%{opacity:1;transform:none}}\
#srAutoBatch266{margin-top:8px;padding:8px;border:1px solid #314a70;border-radius:12px;background:#0d1728}.srBatchBtns266{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:6px}.srBatch266{appearance:none;border:1px solid #405a80;background:#111d31;color:#b8c6dc;border-radius:9px;padding:7px 2px;font-size:10px;font-weight:900}.srBatch266.on{border-color:#e8b44a;color:#ffe2a0;background:#2a210d;box-shadow:0 0 0 1px #e8b44a55 inset}\
@media(max-width:390px){#srForgeLoot267{height:58px;max-height:58px}#srForgeLoot267 .srForgeStackCard267{top:4px;width:44px;height:49px}#srForgeLoot267 .srForgeStackCard267 img{width:29px;height:29px}#srForgeLoot267 .srForgeTransientCard267{height:50px;top:4px}}\
@media(prefers-reduced-motion:reduce){#srForgeLoot267 *{animation:none!important;transition:opacity .1s linear!important}.srForgeTransientCard267.enter{opacity:1!important;transform:none!important;filter:none!important}}';document.head.appendChild(st);
window.__srForgeUXV267={batch:batch,clear:function(){resetUI(true);},kept:function(){return kept.slice();},version:267};
})();