const fs=require('fs'),assert=require('assert');
const s=fs.readFileSync('campaign-early-rebalance-v449.js','utf8');
assert(s.includes('FIRST=2, FIRST_END=84'),'first window must be Facile 1-2 through 5-4');
assert(s.includes('SECOND_START=85, SECOND_END=99'),'second window must contain exactly the next 15 stages');
assert(s.includes('{hp:0.60,dmg:1.60,band:1}'),'first window must be -40% HP / +60% damage');
assert(s.includes('SECOND_DAMAGE_MUL=0.70'),'second window target damage must be -30%');
assert(s.includes('SECOND_ENTRY_DAMAGE_MUL=0.85'),'5-5 must keep the continuity guard');
assert(s.includes("if(f===SECOND_START)return {hp:0.70,dmg:SECOND_ENTRY_DAMAGE_MUL,band:2,continuityGuard:true}"),'5-5 must use the continuity guard');
assert(s.includes("if(f>SECOND_START&&f<=SECOND_END)return {hp:0.70,dmg:SECOND_DAMAGE_MUL,band:2}"),'5-6 through 5-19 must use full -30% damage');
assert(s.includes("mode!=='campaign'"),'authority must not modify raids');
assert(s.includes('opts.megaBoss'),'authority must not modify Mega-Bosses');
assert(s.includes('postBossException:postBoss'),'post-Boss easing exception must remain explicit');
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('campaign-tier-balance-v352.js')&&html.indexOf('campaign-early-rebalance-v449.js')>html.indexOf('campaign-tier-balance-v352.js'),'V449 must load after Campaign smoothing');
assert(html.includes('function chain(list,done){var i=0;function next()')&&html.includes('load(list[i++],next);}next();}'),'dynamic loader must remain intact');
console.log('V465 early Campaign rebalance contract OK');
