from pathlib import Path

p = Path('game-4.js')
s = p.read_text(encoding='utf-8')

anchor = '''  const previewDelta = hasPreview ? Math.round(previewPower - S.power) : 0;\n  const dockStat = (label,cur,next) => '<div class="dockStat"><div class="n">'+label+'</div><div class="v" style="color:#78B7FF">'+cur+' → '+next+'</div></div>';'''
insert = '''  const previewDelta = hasPreview ? Math.round(previewPower - S.power) : 0;\n  // V495: comparison-only scores. These never feed combat, computePower or saves.\n  // Offense estimates sustained output; Survival estimates effective durability.\n  const equipCompareScores = (d) => {\n    const critExpected = 1 + Math.max(0, Number(d.critChance)||0) / 100 * Math.max(0, (Number(d.critMult)||1) - 1);\n    const doubleExpected = 1 + Math.max(0, Number(d.doubleAtk)||0) / 100;\n    const styleBonus = 1 + Math.max(0, d.weapon === "arc" ? Number(d.rangedDmg)||0 : Number(d.meleeDmg)||0) / 100;\n    const offense = Math.max(0, Number(d.damage)||0) * Math.max(.01, Number(d.attackSpeed)||1) * critExpected * doubleExpected * styleBonus;\n    const defKeep = Math.max(.05, 1 - Math.min(95, Math.max(0, Number(d.defenseReduction)||0)) / 100);\n    const redKeep = Math.max(.05, 1 - Math.min(95, Math.max(0, Number(d.dmgRed)||0)) / 100);\n    const blockKeep = Math.max(.05, 1 - Math.min(95, Math.max(0, Number(d.blockChance)||0)) / 200);\n    const sustain = 1 + Math.max(0, Number(d.regen)||0) / 100 + Math.max(0, Number(d.lifesteal)||0) / 200;\n    const survival = Math.max(0, Number(d.maxHP)||0) / (defKeep * redKeep * blockKeep) * sustain;\n    return { offense: Math.round(offense), survival: Math.round(survival) };\n  };\n  const compareNow = equipCompareScores(D), compareNext = equipCompareScores(d2);\n  const comparePct = (a,b) => a > 0 ? ((b-a)/a)*100 : (b>0 ? 100 : 0);\n  const offensePct = comparePct(compareNow.offense, compareNext.offense);\n  const survivalPct = comparePct(compareNow.survival, compareNext.survival);\n  const verdict = !hasPreview ? null : (() => {\n    const p = previewDelta;\n    if (p > 0 && offensePct >= -1 && survivalPct >= -1) return {t:"Amélioration globale",c:"#63E889",d:"Plus de puissance sans sacrifice important en attaque ou survie."};\n    if (offensePct > 2 && survivalPct < -2) return {t:"Plus offensif",c:"#F5C542",d:"Tu gagnes en dégâts, mais tu sacrifies de la survie."};\n    if (survivalPct > 2 && offensePct < -2) return {t:"Plus défensif",c:"#72A7E8",d:"Tu gagnes en survie, mais tu sacrifies de l'offense."};\n    if (p < 0 && offensePct <= 1 && survivalPct <= 1) return {t:"Régression globale",c:"#FF6B72",d:"Cette configuration n'apporte pas de gain compensatoire notable."};\n    return {t:"Choix situationnel",c:"#C79BFF",d:"Le meilleur choix dépend du combat : compare l'offense et la survie avant d'équiper."};\n  })();\n  const scoreCell = (label,cur,next,color) => '<div class="col" style="width:33.33%;padding:6px 3px"><div class="mute tiny b">'+label+'</div><div class="bb" style="color:'+color+'">'+fmt(cur)+'</div>'+(hasPreview?'<div class="tiny bb" style="color:#78B7FF">→ '+fmt(next)+'</div>':'')+'</div>';\n  const dockStat = (label,cur,next) => '<div class="dockStat"><div class="n">'+label+'</div><div class="v" style="color:#78B7FF">'+cur+' → '+next+'</div></div>';'''
if anchor not in s:
    raise SystemExit('V495 anchor previewDelta not found')
s = s.replace(anchor, insert, 1)

old = '''    '<div class="card frame"><div class="between"><div><div class="mute tiny b">PUISSANCE TOTALE</div><div class="bb gt" style="font-size:22px">'+fmt(S.power)+'</div></div>' +\n    (hasPreview ? '<div class="col" style="align-items:flex-end"><div class="mute tiny b">APRÈS TEST</div><div class="bb" style="font-size:20px;color:'+(previewDelta>=0?'#63E889':'#FF6B72')+'">'+fmt(previewPower)+' ('+(previewDelta>=0?'+':'')+fmt(previewDelta)+')</div></div>' : '') + '</div></div>' +'''
new = '''    '<div class="card frame"><div class="between"><div><div class="mute tiny b">PUISSANCE GLOBALE</div><div class="bb gt" style="font-size:22px">'+fmt(S.power)+'</div></div>' +\n    (hasPreview ? '<div class="col" style="align-items:flex-end"><div class="mute tiny b">APRÈS TEST</div><div class="bb" style="font-size:20px;color:'+(previewDelta>=0?'#63E889':'#FF6B72')+'">'+fmt(previewPower)+' ('+(previewDelta>=0?'+':'')+fmt(previewDelta)+')</div></div>' : '') + '</div>' +\n    '<div class="row mt6" style="flex-wrap:wrap;border-top:1px solid var(--line);padding-top:4px">'+\n      scoreCell('Puissance',S.power,previewPower,'var(--goldLit)')+scoreCell('Offense',compareNow.offense,compareNext.offense,'#F0883E')+scoreCell('Survie',compareNow.survival,compareNext.survival,'#72A7E8')+'</div>'+\n    (verdict?'<div class="notice mt6" style="border-color:'+verdict.c+'66"><div class="bb tiny" style="color:'+verdict.c+'">'+verdict.t+'</div><div class="mute tiny mt2">'+verdict.d+'</div></div>':'')+'</div>' +'''
if old not in s:
    raise SystemExit('V495 power card anchor not found')
s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8')
print('V495 comparator patch applied')
